import { useEffect, useState } from "react";
import { fetchAlerts } from "../../services/alertsApi";
import { useRealtime } from "../../hooks/useRealtime";
import { useThreat } from "../../context/ThreatContext";
import { useNavigate } from "react-router-dom";

export default function Alerts() {
  const [alerts, setAlerts] = useState([]);
  const { setFocusedThreat } = useThreat();
  const navigate = useNavigate();

  /* ---------------- REAL-TIME ALERT STREAM ---------------- */
  useRealtime((payload) => {
    if (payload.type === "alert") {
      setAlerts((prev) => [payload.data, ...prev]);
    }
  });

  /* ---------------- INITIAL LOAD + FALLBACK POLLING ---------------- */
  useEffect(() => {
    const loadAlerts = async () => {
      try {
        const data = await fetchAlerts();
        setAlerts(data.alerts || []);
      } catch (err) {
        console.error("Failed to fetch alerts", err);
      }
    };

    loadAlerts();
    const interval = setInterval(loadAlerts, 3000);

    return () => clearInterval(interval);
  }, []);

  return (
    <div style={styles.page}>
      <h2>Security Alerts</h2>
      <p style={styles.subtitle}>
        Real-time alerts generated by backend intelligence.
      </p>

      <div style={styles.panel}>
        <table style={styles.table}>
          <thead>
            <tr>
              <th>Severity</th>
              <th>Score</th>
              <th>ML</th>
              <th>Source</th>
              <th>Time</th>
            </tr>
          </thead>

          <tbody>
            {alerts.map((alert) => (
              <tr
                key={alert.id}
                style={{ cursor: "pointer" }}
                onClick={() => {
                  setFocusedThreat(alert);
                  navigate("/dashboard/threats");
                }}
              >
                <td style={{ color: severityColor(alert.severity) }}>
                  {alert.severity}
                </td>
                <td>{alert.score.toFixed(2)}</td>
                <td>
                  {typeof alert.mlScore === "number"
                    ? alert.mlScore.toFixed(2)
                    : "-"}
                </td>
                <td>{alert.source}</td>
                <td>
                  {new Date(alert.time).toLocaleTimeString()}
                </td>
              </tr>
            ))}

            {alerts.length === 0 && (
              <tr>
                <td colSpan="5" style={{ opacity: 0.6 }}>
                  No active alerts
                </td>
              </tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  );
}

/* ---------------- HELPERS ---------------- */
function severityColor(level) {
  if (level === "Critical") return "#ff4d4d";
  if (level === "Medium") return "#ffd24d";
  return "#00ffff";
}

/* ---------------- STYLES ---------------- */
const styles = {
  page: {
    display: "flex",
    flexDirection: "column",
    gap: "20px",
  },
  subtitle: {
    opacity: 0.7,
  },
  panel: {
    padding: "16px",
    borderRadius: "12px",
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  table: {
    width: "100%",
    borderCollapse: "collapse",
  },
};
